window.PAINTINGS = [
  {
    "id": 1,
    "title": "Oudste siel",
    "category": "nature",
    "categoryLabel": "Nature",
    "description": "",
    "image": "assets/images/oudste-siel.jpeg",
    "status": "for-sale",
    "price": "R10 500",
    "dimensions": "70 × 100 cm",
    "medium": "Oil on Stretched Canvas"
  },
  {
    "id": 2,
    "title": "Quiet King",
    "category": "wildlife",
    "categoryLabel": "Wildlife",
    "description": "",
    "image": "assets/images/quiet-king.jpeg",
    "status": "for-sale",
    "price": "R7 300",
    "dimensions": "70 × 60 cm",
    "medium": "Oil on Stretched Canvas"
  },
  {
    "id": 3,
    "title": "Ongewankel",
    "category": "farm-animals",
    "categoryLabel": "Farm Animals",
    "description": "",
    "image": "assets/images/ongewankel.jpeg",
    "status": "for-sale",
    "price": "R10 500",
    "dimensions": "70 × 100 cm",
    "medium": "Oil on Stretched Canvas"
  },
  {
    "id": 4,
    "title": "Stormloop",
    "category": "farm-animals",
    "categoryLabel": "Farm Animals",
    "description": "",
    "image": "assets/images/stormloop.jpeg",
    "status": "for-sale",
    "price": "R18 000",
    "dimensions": "100 × 120 cm",
    "medium": "Oil on Stretched Canvas"
  },
  {
    "id": 5,
    "title": "Circle of Belonging",
    "category": "farm-animals",
    "categoryLabel": "Farm Animals",
    "description": "",
    "image": "assets/images/circle-of-belonging.jpeg",
    "status": "for-sale",
    "price": "R11 800",
    "dimensions": "100 cm round",
    "medium": "Oil on Wood Board"
  },
  {
    "id": 6,
    "title": "Genoeg",
    "category": "farm-animals",
    "categoryLabel": "Farm Animals",
    "description": "",
    "image": "assets/images/genoeg.jpeg",
    "status": "for-sale",
    "price": "R900",
    "dimensions": "20 × 30 cm",
    "medium": "Oil on Stretched Canvas"
  },
  {
    "id": 7,
    "title": "Bly naby",
    "category": "farm-animals",
    "categoryLabel": "Farm Animals",
    "description": "",
    "image": "assets/images/bly-naby.jpeg",
    "status": "for-sale",
    "price": "R900",
    "dimensions": "20 × 30 cm",
    "medium": "Oil on Stretched Canvas"
  },
  {
    "id": 8,
    "title": "Die Komitee",
    "category": "farm-animals",
    "categoryLabel": "Farm Animals",
    "description": "",
    "image": "assets/images/die-komitee.jpeg",
    "status": "for-sale",
    "price": "R1 900",
    "dimensions": "30 × 42 cm",
    "medium": "Oil on Stretched Canvas"
  },
  {
    "id": 9,
    "title": "Sonneblom kind 1",
    "category": "human",
    "categoryLabel": "Human",
    "description": "",
    "image": "assets/images/sonneblom-kind-1.jpeg",
    "status": "for-sale",
    "price": "R1 800",
    "dimensions": "40 × 30 cm",
    "medium": "Oil on Stretched Canvas"
  },
  {
    "id": 10,
    "title": "Sonneblom kind 2",
    "category": "human",
    "categoryLabel": "Human",
    "description": "",
    "image": "assets/images/sonneblom-kind-2.jpeg",
    "status": "for-sale",
    "price": "R1 800",
    "dimensions": "40 × 30 cm",
    "medium": "Oil on Stretched Canvas"
  },
  {
    "id": 11,
    "title": "Kinder liefde - rooi stewels",
    "category": "human",
    "categoryLabel": "Human",
    "description": "",
    "image": "assets/images/kinder-liefde-rooi-stewels.jpeg",
    "status": "for-sale",
    "price": "R1 800",
    "dimensions": "30 × 40 cm",
    "medium": "Oil on Stretched Canvas"
  },
  {
    "id": 100,
    "title": "",
    "category": "human",
    "categoryLabel": "Human",
    "description": "",
    "image": "assets/images/previous-01-human.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 101,
    "title": "",
    "category": "farm-animals",
    "categoryLabel": "Farm Animals",
    "description": "",
    "image": "assets/images/previous-02-farm-animals.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 102,
    "title": "",
    "category": "human",
    "categoryLabel": "Human",
    "description": "",
    "image": "assets/images/previous-03-human.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 103,
    "title": "",
    "category": "nature",
    "categoryLabel": "Nature",
    "description": "",
    "image": "assets/images/previous-04-nature.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 104,
    "title": "",
    "category": "wildlife",
    "categoryLabel": "Wildlife",
    "description": "",
    "image": "assets/images/previous-05-wildlife.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 105,
    "title": "",
    "category": "human",
    "categoryLabel": "Human",
    "description": "",
    "image": "assets/images/previous-06-human.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 106,
    "title": "",
    "category": "farm-animals",
    "categoryLabel": "Farm Animals",
    "description": "",
    "image": "assets/images/previous-07-farm-animals.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 107,
    "title": "",
    "category": "wildlife",
    "categoryLabel": "Wildlife",
    "description": "",
    "image": "assets/images/previous-08-wildlife.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 108,
    "title": "",
    "category": "wildlife",
    "categoryLabel": "Wildlife",
    "description": "",
    "image": "assets/images/previous-09-wildlife.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 109,
    "title": "",
    "category": "human",
    "categoryLabel": "Human",
    "description": "",
    "image": "assets/images/previous-10-human.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 110,
    "title": "",
    "category": "wildlife",
    "categoryLabel": "Wildlife",
    "description": "",
    "image": "assets/images/previous-11-wildlife.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 111,
    "title": "",
    "category": "human",
    "categoryLabel": "Human",
    "description": "",
    "image": "assets/images/previous-12-human.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 112,
    "title": "",
    "category": "wildlife",
    "categoryLabel": "Wildlife",
    "description": "",
    "image": "assets/images/previous-13-wildlife.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 113,
    "title": "",
    "category": "wildlife",
    "categoryLabel": "Wildlife",
    "description": "",
    "image": "assets/images/previous-14-wildlife.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 114,
    "title": "",
    "category": "farm-animals",
    "categoryLabel": "Farm Animals",
    "description": "",
    "image": "assets/images/previous-15-farm-animals.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 115,
    "title": "",
    "category": "human",
    "categoryLabel": "Human",
    "description": "",
    "image": "assets/images/previous-16-human.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 116,
    "title": "",
    "category": "human",
    "categoryLabel": "Human",
    "description": "",
    "image": "assets/images/previous-17-human.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 117,
    "title": "",
    "category": "wildlife",
    "categoryLabel": "Wildlife",
    "description": "",
    "image": "assets/images/previous-18-wildlife.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 118,
    "title": "",
    "category": "human",
    "categoryLabel": "Human",
    "description": "",
    "image": "assets/images/previous-19-human.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 119,
    "title": "",
    "category": "wildlife",
    "categoryLabel": "Wildlife",
    "description": "",
    "image": "assets/images/previous-20-wildlife.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 120,
    "title": "",
    "category": "human",
    "categoryLabel": "Human",
    "description": "",
    "image": "assets/images/previous-21-human.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  },
  {
    "id": 121,
    "title": "",
    "category": "wildlife",
    "categoryLabel": "Wildlife",
    "description": "",
    "image": "assets/images/previous-22-wildlife.jpeg",
    "status": "previous",
    "price": "",
    "dimensions": "",
    "medium": ""
  }
];
